blank_issues_enabled: true
contact_links:
  - name: Rockerz Support
    url: https://t.me/rockerz_Support
    about: Direct chat on non-inquiries subjects.
  - name: Documentation
    url: https://Rock.tech/
    about: Documentation for getting started with bot.
